CREATE INDEX "FLASHLIGHT"."LOCKSHELD_LOCKACQUIRED_INDEX" ON "FLASHLIGHT"."LOCKSHELD" ("LOCKACQUIRED")
<<>>
CREATE INDEX "FLASHLIGHT"."LOCKSHELD_LOCKHELD_INDEX" ON "FLASHLIGHT"."LOCKSHELD" ("LOCKHELD")
<<>>
CREATE INDEX "FLASHLIGHT"."TRACE_STOP_INDEX" ON "FLASHLIGHT"."TRACE" ("STOP")
<<>>
CREATE INDEX "FLASHLIGHT"."TRACE_START_INDEX" ON "FLASHLIGHT"."TRACE" ("START")
<<>>
CREATE INDEX "FLASHLIGHT"."LOCKDURATION_STOP_INDEX" ON "FLASHLIGHT"."LOCKDURATION" ("STOP")
<<>>
CREATE INDEX "FLASHLIGHT"."LOCKDURATION_START_INDEX" ON "FLASHLIGHT"."LOCKDURATION" ("START")
<<>>
CREATE INDEX "FLASHLIGHT"."OBJECT_FLAG_INDEX" ON "FLASHLIGHT"."OBJECT" ("FLAG")
<<>>
CREATE INDEX "FLASHLIGHT"."ACCESS_TS_INDEX" ON "FLASHLIGHT"."ACCESS" ("TS")
<<>>
CREATE INDEX "FLASHLIGHT"."FIELD_STATIC_INDEX" ON "FLASHLIGHT"."FIELD" ("STATIC")
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCELOCKSET" ADD PRIMARY KEY ("RUN", "FIELD", "RECEIVER", "LOCK")
<<>>
ALTER TABLE "FLASHLIGHT"."RUN" ADD PRIMARY KEY ("RUN")
<<>>
ALTER TABLE "FLASHLIGHT"."LOCK" ADD PRIMARY KEY ("RUN", "ID")
<<>>
ALTER TABLE "FLASHLIGHT"."TRACE" ADD PRIMARY KEY ("RUN", "ID")
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKDURATION" ADD PRIMARY KEY ("ID")
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCETHREAD" ADD PRIMARY KEY ("RUN", "FIELD", "RECEIVER", "THREAD")
<<>>
ALTER TABLE "FLASHLIGHT"."FIELD" ADD PRIMARY KEY ("RUN", "ID")
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDSTATICTHREAD" ADD PRIMARY KEY ("RUN", "FIELD", "THREAD")
<<>>
ALTER TABLE "FLASHLIGHT"."OBJECT" ADD PRIMARY KEY ("RUN", "ID")
<<>>
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD PRIMARY KEY ("ID")
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDLOCKSET" ADD PRIMARY KEY ("RUN", "FIELD", "LOCK")
<<>>
ALTER TABLE "FLASHLIGHT"."SITE" ADD PRIMARY KEY ("RUN", "ID")
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCELOCKSET" ADD CONSTRAINT "FIELDINSTANCELOCKSET_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCELOCKSET" ADD CONSTRAINT "FIELDINSTANCELOCKSET_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCELOCKSET" ADD CONSTRAINT "FIELDINSTANCELOCKSET_LOCK_FK" FOREIGN KEY ("RUN", "LOCK") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCELOCKSET" ADD CONSTRAINT "FIELDINSTANCELOCKSET_RECEIVER_FK" FOREIGN KEY ("RUN", "RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCK" ADD CONSTRAINT "LOCK_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCK" ADD CONSTRAINT "LOCK_INTHREAD_FK" FOREIGN KEY ("RUN", "INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCK" ADD CONSTRAINT "LOCK_SITE_FK" FOREIGN KEY ("RUN", "SITE") REFERENCES "FLASHLIGHT"."SITE" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCK" ADD CONSTRAINT "LOCK_LOCK_FK" FOREIGN KEY ("RUN", "LOCK") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKSHELD" ADD CONSTRAINT "LOCKSHELD_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKSHELD" ADD CONSTRAINT "LOCKSHELD_INTHREAD_FK" FOREIGN KEY ("RUN", "INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKSHELD" ADD CONSTRAINT "LOCKSHELD_LOCK_FK" FOREIGN KEY ("RUN", "LOCKHELD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKSHELD" ADD CONSTRAINT "LOCKSHELD_LOCK2_FK" FOREIGN KEY ("RUN", "LOCKACQUIRED") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKSHELD" ADD CONSTRAINT "LOCKSHELD_ACQUIREDEVENT_FK" FOREIGN KEY ("RUN", "LOCKEVENT") REFERENCES "FLASHLIGHT"."LOCK" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."BADPUBLISH" ADD CONSTRAINT "BADPUBLISH_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."BADPUBLISH" ADD CONSTRAINT "BADPUBLISH_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."BADPUBLISH" ADD CONSTRAINT "BADPUBLISH_RECEIVER_FK" FOREIGN KEY ("RUN", "RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."RWLOCK" ADD CONSTRAINT "RWLOCK_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."RWLOCK" ADD CONSTRAINT "RWLOCK_ID_FK" FOREIGN KEY ("RUN", "ID") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."RWLOCK" ADD CONSTRAINT "RWLOCK_READLOCK_FK" FOREIGN KEY ("RUN", "READLOCK") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."RWLOCK" ADD CONSTRAINT "RWLOCK_WRITELOCK_FK" FOREIGN KEY ("RUN", "WRITELOCK") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."TRACE" ADD CONSTRAINT "TRACE_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."TRACE" ADD CONSTRAINT "TRACE_INTHREAD_FK" FOREIGN KEY ("RUN", "INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."TRACE" ADD CONSTRAINT "TRACE_SITE_FK" FOREIGN KEY ("RUN", "SITE") REFERENCES "FLASHLIGHT"."SITE" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKTHREADSTATS" ADD CONSTRAINT "LOCKTHREADSTATS_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKTHREADSTATS" ADD CONSTRAINT "LOCKTHREADSTATS_ACQUIREDEVENT_FK" FOREIGN KEY ("RUN", "LOCKEVENT") REFERENCES "FLASHLIGHT"."LOCK" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."INTERESTINGFIELD" ADD CONSTRAINT "INTERESTINFIELD_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."INTERESTINGFIELD" ADD CONSTRAINT "INTERESTINGFIELD_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."INTERESTINGFIELD" ADD CONSTRAINT "INTERESTINGFIELD_RECEIVER_FK" FOREIGN KEY ("RUN", "RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKDURATION" ADD CONSTRAINT "LOCKDURATION_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKDURATION" ADD CONSTRAINT "LOCKDURATION_INTHREAD_FK" FOREIGN KEY ("RUN", "INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKDURATION" ADD CONSTRAINT "LOCKDURATION_LOCK_FK" FOREIGN KEY ("RUN", "LOCK") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKDURATION" ADD CONSTRAINT "LOCKDURATION_BLOCKEDEVENT_FK" FOREIGN KEY ("RUN", "STARTEVENT") REFERENCES "FLASHLIGHT"."LOCK" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKDURATION" ADD CONSTRAINT "LOCKDURATION_ACQUIREDEVENT_FK" FOREIGN KEY ("RUN", "STOPEVENT") REFERENCES "FLASHLIGHT"."LOCK" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCETHREAD" ADD CONSTRAINT "FIELDINSTANCETHREAD_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCETHREAD" ADD CONSTRAINT "FIELDINSTANCETHREAD_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCETHREAD" ADD CONSTRAINT "FIELDINSTANCETHREAD_RECEIVER_FK" FOREIGN KEY ("RUN", "RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDINSTANCETHREAD" ADD CONSTRAINT "FIELDINSTANCETHREAD_THREAD_FK" FOREIGN KEY ("RUN", "THREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELD" ADD CONSTRAINT "FIELD_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELD" ADD CONSTRAINT "FIELD_DECLARINGTYPE_FK" FOREIGN KEY ("RUN", "DECLARINGTYPE") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKCYCLE" ADD CONSTRAINT "LOCKCYCLE_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKCYCLE" ADD CONSTRAINT "LOCKCYCLE_LOCKHELD_FK" FOREIGN KEY ("RUN", "LOCKHELD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."LOCKCYCLE" ADD CONSTRAINT "LOCKCYCLE_LOCKACQUIRED_FK" FOREIGN KEY ("RUN", "LOCKACQUIRED") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDSTATICTHREAD" ADD CONSTRAINT "FIELDSTATICTHREAD_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDSTATICTHREAD" ADD CONSTRAINT "FIELDSTATICTHREAD_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDSTATICTHREAD" ADD CONSTRAINT "FIELDSTATICTHREAD_THREAD_FK" FOREIGN KEY ("RUN", "THREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."OBJECT" ADD CONSTRAINT "OBJECT_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."OBJECT" ADD CONSTRAINT "OBJECT_TYPE_FK" FOREIGN KEY ("RUN", "TYPE") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD CONSTRAINT "ACCESS_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD CONSTRAINT "ACCESS_INTHREAD_FK" FOREIGN KEY ("RUN", "INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD CONSTRAINT "ACCESS_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD CONSTRAINT "ACCESS_RECEIVER_FK" FOREIGN KEY ("RUN", "RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD CONSTRAINT "ACCESS_SITE_FK" FOREIGN KEY ("RUN", "SITE") REFERENCES "FLASHLIGHT"."SITE" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDLOCKSET" ADD CONSTRAINT "FIELDLOCKSET_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDLOCKSET" ADD CONSTRAINT "FIELDLOCKSET_FIELD_FK" FOREIGN KEY ("RUN", "FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."FIELDLOCKSET" ADD CONSTRAINT "FIELDLOCKSET_LOCK_FK" FOREIGN KEY ("RUN", "LOCK") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."SITE" ADD CONSTRAINT "SITE_RUN_FK" FOREIGN KEY ("RUN") REFERENCES "FLASHLIGHT"."RUN" ("RUN") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."SITE" ADD CONSTRAINT "SITE_INCLASS_FK" FOREIGN KEY ("RUN","INCLASS") REFERENCES "FLASHLIGHT"."OBJECT" ("RUN", "ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>

