ALTER TABLE ILOCKDURATION DROP CONSTRAINT ILOCKDURATION_BlockedEvent_FK
<<>>
ALTER TABLE ILOCKDURATION DROP CONSTRAINT ILOCKDURATION_AcquiredEvent_FK
<<>>
ALTER TABLE ILOCKDURATION ADD CONSTRAINT ILOCKDURATION_BlockedEvent_FK FOREIGN KEY (Run, StartEvent) REFERENCES LOCK (Run, Id)
<<>>
ALTER TABLE ILOCKDURATION ADD CONSTRAINT ILOCKDURATION_AcquiredEvent_FK FOREIGN KEY (Run, StopEvent) REFERENCES LOCK (Run, Id)
<<>>
ALTER TABLE ILOCKSHELD DROP CONSTRAINT ILOCKSHELD_AcquiredEvent_FK
<<>>
ALTER TABLE ILOCKSHELD ADD CONSTRAINT ILOCKSHELD_AcquiredEvent_FK FOREIGN KEY (Run, LockEvent) REFERENCES LOCK (Run, Id)
<<>>
ALTER TABLE ILOCKTHREADSTATS DROP CONSTRAINT ILOCKTHREADSTATS_AcquiredEvent_FK
<<>>
ALTER TABLE ILOCKTHREADSTATS ADD CONSTRAINT ILOCKTHREADSTATS_AcquiredEvent_FK FOREIGN KEY (Run, LockEvent) REFERENCES LOCK (Run, Id)
<<>>