ALTER TABLE "FLASHLIGHT"."BADHAPPENSBEFORE" ADD CONSTRAINT "BHB_FIELD_FK" FOREIGN KEY ("FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."BADHAPPENSBEFORE" ADD CONSTRAINT "BHB_OBJECT_FK" FOREIGN KEY ("RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>

