CREATE INDEX "FLASHLIGHT"."HAPPENSBEFOREVOLATILEREAD_TS_INDEX" ON "FLASHLIGHT"."HAPPENSBEFOREVOLATILEREAD" ("TS")
<<>>
CREATE INDEX "FLASHLIGHT"."HAPPENSBEFOREVOLATILEWRITE_TS_INDEX" ON "FLASHLIGHT"."HAPPENSBEFOREVOLATILEWRITE" ("TS")
<<>>
ALTER TABLE "FLASHLIGHT"."HAPPENSBEFOREVOLATILEREAD" ADD CONSTRAINT "HBVR_THREAD_FK" FOREIGN KEY ("INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."HAPPENSBEFOREVOLATILEREAD" ADD CONSTRAINT "HBVR_FIELD_FK" FOREIGN KEY ("FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."HAPPENSBEFOREVOLATILEWRITE" ADD CONSTRAINT "HBVW_THREAD_FK" FOREIGN KEY ("INTHREAD") REFERENCES "FLASHLIGHT"."OBJECT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
ALTER TABLE "FLASHLIGHT"."HAPPENSBEFOREVOLATILEWRITE" ADD CONSTRAINT "HBVW_FIELD_FK" FOREIGN KEY ("FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
<<>>
