ALTER TABLE "FLASHLIGHT"."BADHAPPENSBEFORE" ADD CONSTRAINT "BHB_FIELD_FK" FOREIGN KEY ("FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("ID")
<<>>
ALTER TABLE "FLASHLIGHT"."BADHAPPENSBEFORE" ADD CONSTRAINT "BHB_OBJECT_FK" FOREIGN KEY ("RECEIVER") REFERENCES "FLASHLIGHT"."OBJECT" ("ID") 
<<>>
ALTER TABLE "FLASHLIGHT"."CLASSINIT" ADD CONSTRAINT "CI_CLASS_FK" FOREIGN KEY ("OBJ") REFERENCES "FLASHLIGHT"."OBJECT" ("ID")
<<>>
CREATE INDEX "FLASHLIGHT"."CLASSINIT_INDEX" ON "FLASHLIGHT"."CLASSINIT" ("INTHREAD", "TS")
<<>>
ALTER TABLE "FLASHLIGHT"."CLASSACCESS" ADD CONSTRAINT "CA_CLASS_FK" FOREIGN KEY ("OBJ") REFERENCES "FLASHLIGHT"."OBJECT" ("ID")
<<>>
CREATE INDEX "FLASHLIGHT"."CLASSACCESS_INDEX" ON "FLASHLIGHT"."CLASSACCESS" ("INTHREAD", "TS")
<<>>
