CREATE INDEX "FLASHLIGHT"."HAPPENSBEFOREVOLATILEREAD_INDEX" ON 
       "FLASHLIGHT"."HAPPENSBEFOREVOLATILEREAD" ("INTHREAD","TS")
<<>>
CREATE INDEX "FLASHLIGHT"."HAPPENSBEFOREVOLATILEWRITE_INDEX" ON 
       "FLASHLIGHT"."HAPPENSBEFOREVOLATILEWRITE" ("INTHREAD","TS")
<<>>

