
ALTER TABLE OBJECT ADD COLUMN FLAG CHAR(1)
<<>>
UPDATE OBJECT
  SET Flag = CASE WHEN ThreadName IS NOT NULL THEN 'T'
                  WHEN ClassName  IS NOT NULL THEN 'C'
                  ELSE 'O'
             END
<<>>
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_FLAG_CN CHECK (FLAG IS NOT NULL AND FLAG IN ('C','O','T'))
<<>>
CREATE INDEX OBJECT_FLAG_INDEX ON OBJECT (FLAG)
<<>>