
DROP TABLE LOCKDURATION
<<>>
create table LOCKDURATION ( -- derived from LOCK
  Id           BIGINT    NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Run          INT       NOT NULL CONSTRAINT LOCKDURATION_Run_FK REFERENCES RUN (Run),
  InThread     BIGINT    NOT NULL,
  Lock         BIGINT    NOT NULL,
  Start        TIMESTAMP NOT NULL,
  StartEvent   BIGINT    NOT NULL,
  Stop         TIMESTAMP NOT NULL,
  StopEvent    BIGINT    NOT NULL,
  Duration     BIGINT    NOT NULL, -- redundant w/ Start and Stop
  State        VARCHAR(10) NOT NULL CONSTRAINT LOCKDURATION_State_CN CHECK
    (State IN ('BLOCKING', 'HOLDING', 'WAITING')),
  CONSTRAINT LOCKDURATION_InThread_FK FOREIGN KEY (Run, InThread) REFERENCES OBJECT (Run, Id),
  CONSTRAINT LOCKDURATION_Lock_FK FOREIGN KEY (Run, Lock) REFERENCES OBJECT (Run, Id),
  CONSTRAINT LOCKDURATION_BlockedEvent_FK FOREIGN KEY (Run, StartEvent) REFERENCES LOCK (Run, Id),
  CONSTRAINT LOCKDURATION_AcquiredEvent_FK FOREIGN KEY (Run, StopEvent) REFERENCES LOCK (Run, Id)
)
<<>>
CREATE INDEX LOCKDURATION_Start_INDEX ON LOCKDURATION (Start)
<<>>
CREATE INDEX LOCKDURATION_Stop_INDEX ON LOCKDURATION (Stop)
<<>>
DROP TABLE ACCESS
<<>>
create table ACCESS ( -- field access (read/write) events
  ID                BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Run               INT          NOT NULL CONSTRAINT ACCESS_Run_FK REFERENCES RUN (Run),
  TS                TIMESTAMP    NOT NULL,
  InThread          BIGINT       NOT NULL,
  InClass           BIGINT       NOT NULL,
  AtLine            INT          NOT NULL,
  Field             BIGINT       NOT NULL,
  RW                CHAR(1)      NOT NULL CONSTRAINT ACCESS_RW_CN CHECK (RW IN ('R', 'W')),
  Receiver          BIGINT,
  UnderConstruction CHAR(1) NOT NULL CONSTRAINT ACCESS_UnderConstruction_CN CHECK (UnderConstruction IN ('Y','N')),
  CONSTRAINT ACCESS_InThread_FK FOREIGN KEY (Run, InThread) REFERENCES OBJECT (Run, Id),
  CONSTRAINT ACCESS_Field_FK FOREIGN KEY (Run, Field) REFERENCES FIELD (Run, Id),
  CONSTRAINT ACCESS_Receiver_FK FOREIGN KEY (Run, Receiver) REFERENCES OBJECT (Run, Id),
  CONSTRAINT ACCESS_InClass_FK FOREIGN KEY (Run, Receiver) REFERENCES OBJECT (Run, Id)
)
<<>>
CREATE INDEX ACCESS_TS_INDEX ON ACCESS (TS)
<<>>